name: "Remy and Dave"
descripiton: "Remy and Dave's Wedding Website"
author: "David Klein"
url: "http://localhost:4000"
permalink: pretty

plugins: [jekyll-assets]

manifest_name: Remy & David Are Getting Married
manifest_short_name: Remy & Dave
manifest_lang: en
manifest_background_color: white
manifest_display: standalone

exclude: ["node_modules", "gulpfile.js", "Gemfile", "Gemfile.lock", "package.json", "scripts"]

assets:
  digest: true
  sources:
    - "_assets/css"
    - "_assets/js"
